spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/wallet_data
    username: bankperson
    password: walletPassword
  liquibase:
    change-log: db/changelog/main-changelog.xml


